services:
  app:
    build:
      context: .
      args:
        ODOO_VERSION: 17.0
        OCA_ADDONS_PATH: /opt/odoo/oca
        ODOO_CONF_PATH: /etc/odoo/odoo.conf
    network_mode: service:db
    command: sleep infinity
    volumes:
      - workspace-data:/workspace
      - oca-addons:/opt/odoo/oca
      - odoo-config:/etc/odoo

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  odoo-config:
  workspace-data:
  oca-addons:
